 // 圖片和對應文字的資料
 const contentMain = [
    { image: "天同.png", text: "天同"},
    { image: "天機.png", text: "天機"},
    { image: "天府.png", text: "天府"},
    { image: "天梁.png", text: "天梁"},
    { image: "天相.png", text: "天相"},
    { image: "太陰.png", text: "太陰"},
    { image: "廉貞.png", text: "廉貞"},
    { image: "巨門.png", text: "巨門"},
    { image: "武曲.png", text: "武曲"},
    { image: "太陽.png", text: "太陽"},
    { image: "天同天梁.png", text: "天同天梁"},
    { image: "破軍.png", text: "破軍"},
    { image: "紫微.png", text: "紫微"},
    { image: "貪狼.png", text: "貪狼"},
    { image: "天機巨門.png", text: "天機巨門"},
    { image: "天磯天梁.png", text: "天磯天梁"},
    { image: "天機太陰.png", text: "天機太陰"},
    { image: "太陰天同.png", text: "太陰天同"},
    { image: "巨門太陽.png", text: "巨門太陽"},
    { image: "巨門天同.png", text: "巨門天同"},
    { image: "太陽太陰.png", text: "太陽太陰"},
    { image: "廉貞七殺.png", text: "廉貞七殺"},
    { image: "太陽天梁.png", text: "太陽天梁"},
    { image: "廉貞貪狼.png", text: "廉貞貪狼"},
    { image: "廉貞天相.png", text: "廉貞天相"},
    { image: "廉貞天府.png", text: "廉貞天府"},
    { image: "武曲七殺.png", text: "武曲七殺"},
    { image: "廉貞破軍.png", text: "廉貞破軍"},
    { image: "武曲破軍.png", text: "武曲破軍"},
    { image: "武曲貪狼.png", text: "武曲貪狼"},
    { image: "武曲天相.png", text: "武曲天相"},
    { image: "武曲天府.png", text: "武曲天府"},
    { image: "紫微天相.png", text: "紫微天相"},
    { image: "紫微破軍.png", text: "紫微破軍"},
    { image: "紫微七殺.png", text: "紫微七殺"},
    { image: "紫微天府.png", text: "紫微天府"},
    { image: "紫微貪狼.png", text: "紫微貪狼"},
    { image: "天磯天梁倒.png", text: "天磯天梁-倒"},
    { image: "貪狼倒.png", text: "貪狼-倒"},
    { image: "天機倒.png", text: "天機-倒"},
    { image: "天同天梁倒.png", text: "天同天梁-倒"},
    { image: "巨門倒.png", text: "巨門-倒"},
    { image: "太陽倒.png", text: "太陽-倒"},
    { image: "太陰倒.png", text: "太陰-倒"},
    { image: "天機太陰倒.png", text: "天機太陰-倒"},
    { image: "紫微倒.png", text: "紫微-倒"},
    { image: "天梁倒.png", text: "天梁-倒"},
    { image: "廉貞倒.png", text: "廉貞-倒"},
    { image: "太陰天同倒.png", text: "太陰天同-倒"},
    { image: "破軍倒.png", text: "破軍-倒"},
    { image: "武曲倒.png", text: "武曲-倒"},
    { image: "天機巨門倒.png", text: "天機巨門-倒"},
    { image: "太陽天梁倒.png", text: "太陽天梁-倒"},
    { image: "天府倒.png", text: "天府-倒"},
    { image: "天相倒.png", text: "天相-倒"},
    { image: "廉貞貪狼倒.png", text: "廉貞貪狼-倒"},
    { image: "巨門太陽倒.png", text: "巨門太陽-倒"},
    { image: "廉貞天相倒.png", text: "廉貞天相-倒"},
    { image: "武曲七殺倒.png", text: "武曲七殺-倒"},
    { image: "廉貞破軍倒.png", text: "廉貞破軍-倒"},
    { image: "廉貞七殺倒.png", text: "廉貞七殺-倒"},
    { image: "巨門天同倒.png", text: "巨門天同-倒"},
    { image: "紫微貪狼倒.png", text: "紫微貪狼-倒"},
    { image: "武曲破軍倒.png", text: "武曲破軍-倒"},
    { image: "紫微七殺倒.png", text: "紫微七殺-倒"},
    { image: "武曲天相倒.png", text: "武曲天相-倒"},
    { image: "廉貞天府倒.png", text: "廉貞天府-倒"},
    { image: "紫微天府倒.png", text: "紫微天府-倒"},
    { image: "紫微破軍倒.png", text: "紫微破軍-倒"},
    { image: "太陽太陰倒.png", text: "太陽太陰-倒"},
    { image: "武曲天府倒.png", text: "武曲天府-倒"},
    { image: "武曲貪狼倒.png", text: "武曲貪狼-倒"},
    { image: "紫微天相倒.png", text: "紫微天相-倒"},
    { image: "天同倒.png", text: "天同-倒"},
    { image: "七殺倒.png", text: "七殺-倒"},        
    ];

    const contentSupport = [
    { image: "化科.png", text: "化科"},
    { image: "化權.png", text: "化權"},
    { image: "化忌.png", text: "化忌"},
    { image: "天刑.png", text: "天刑"},
    { image: "天鉞.png", text: "天鉞"},
    { image: "左輔.png", text: "左輔"},
    { image: "天魁.png", text: "天魁"},
    { image: "右弼.png", text: "右弼"},
    { image: "火星.png", text: "火星"},
    { image: "文曲.png", text: "文曲"},
    { image: "擎羊.png", text: "擎羊"},
    { image: "文昌.png", text: "文昌"},
    { image: "祿存.png", text: "祿存"},
    { image: "空劫.png", text: "空劫"},
    { image: "紅鸞天喜.png", text: "紅鸞天喜"},
    { image: "陀羅.png", text: "陀羅"},
    { image: "鈴星.png", text: "鈴星"},
    { image: "陰煞.png", text: "陰煞"},
    { image: "天魁倒.png", text: "天魁-倒"},
    { image: "化權倒.png", text: "化權-倒"},
    { image: "化祿倒.png", text: "化祿-倒"},
    { image: "文曲倒.png", text: "文曲-倒"},
    { image: "文昌倒.png", text: "文昌-倒"},
    { image: "右弼倒.png", text: "右弼-倒"},
    { image: "天鉞倒.png", text: "天鉞-倒"},
    { image: "天刑倒.png", text: "天刑-倒"},
    { image: "化忌倒.png", text: "化忌-倒"},
    { image: "火星倒.png", text: "火星-倒"},
    { image: "化科倒.png", text: "化科-倒"},
    { image: "左輔倒.png", text: "左輔-倒"},
    { image: "空劫倒.png", text: "空劫-倒"},
    { image: "祿存倒.png", text: "祿存-倒"},
    { image: "陰煞倒.png", text: "陰煞-倒"},
    { image: "陀羅倒.png", text: "陀羅-倒"},
    { image: "鈴星倒.png", text: "鈴星-倒"},
    { image: "擎羊倒.png", text: "擎羊-倒"},
    { image: "紅鸞天喜倒.png", text: "紅鸞天喜-倒"},        
    ];

    const contentLife = [
    { image: "12養.png", text: "12養"},
    { image: "11胎.png", text: "11胎"},
    { image: "2沐浴.png", text: "2沐浴"},
    { image: "10絕.png", text: "10絕"},
    { image: "4臨官.png", text: "4臨官"},
    { image: "5帝旺.png", text: "5帝旺"},
    { image: "6衰.png", text: "6衰"},
    { image: "7病.png", text: "7病"},
    { image: "3冠帶.png", text: "3冠帶"},
    { image: "8死.png", text: "8死"},
    { image: "9墓.png", text: "9墓"},
    { image: "2沐浴倒.png", text: "2沐浴-倒"},
    { image: "1長生倒.png", text: "1長生-倒"},
    { image: "8死倒.png", text: "8死-倒"},
    { image: "9墓倒.png", text: "9墓-倒"},
    { image: "6衰倒.png", text: "6衰-倒"},
    { image: "7病倒.png", text: "7病-倒"},
    { image: "4臨官倒.png", text: "4臨官-倒"},
    { image: "3冠帶倒.png", text: "3冠帶-倒"},
    { image: "5帝旺倒.png", text: "5帝旺-倒"},
    { image: "10絕倒.png", text: "10絕-倒"},
    { image: "12養倒.png", text: "12養-倒"},
    { image: "11胎倒.png", text: "11胎-倒"}
    ];
    // 隨機顯示圖片和文字
    function showRandomContent() {
        const randomIndex1 = Math.floor(Math.random() * 76);
        const randomIndex2 = Math.floor(Math.random() * 38);
        const randomIndex3 = Math.floor(Math.random() * 24);
        const selectedContentMain = contentMain[randomIndex1];
        const selectedContentSupport = contentSupport[randomIndex2];
        const selectedContentLife = contentLife[randomIndex3];

        // 顯示隨機圖片和文字
        document.getElementById("image1").src = `images/1Main/${selectedContentMain.image}`;
        document.getElementById("text1").textContent = selectedContentMain.text;
        document.getElementById("image2").src = `images/2Support/${selectedContentSupport.image}`;
        document.getElementById("text2").textContent = selectedContentSupport.text;
        document.getElementById("image3").src = `images/3Life/${selectedContentLife.image}`;
        document.getElementById("text3").textContent = selectedContentLife.text;
        console.log("main", selectedContentMain.image, "support", selectedContentSupport.image, "life", selectedContentLife.image);
        console.log("image1", document.getElementById("image1"));
        console.log("image2", document.getElementById("image2"));
        console.log("image3", document.getElementById("image3"));
    }
